### ISSUE TITLE
A tool that supports PS Vita Persona 4 Golden

### ISSUE THREAD

**Issue by PudyJapan** [tge-was-taken/Amicitia#13]
Hi,

Thank you for this awesome tool. However it seems that it doesn't support certain TMX and BIN files from PS Vita Persona 4 Golden. Bustup Bins and card TMX for example doesn't work.

Does Amicitia support those files and I'm doing something wrong?

Is there another tool that supports those files?

Thanks for advance.

**Comment by tge-was-taken** [comment]
Seems to be working by now. Comment to reopen the issue if needed.
