### ISSUE TITLE
Bug on TMX from P4G PC

### ISSUE THREAD

**Issue by Darkmet98** [tge-was-taken/Amicitia#15]
Hello TGE, I've found a small bug on the generated tmx from Amiticia when editing Persona 4 Golden PC

When Amicitia generates a tmx, on the header, the byte on offset 0x2 changes from 1 to 0 and causes this problem
![imagen](https://user-images.githubusercontent.com/13910563/84941574-e2f41a80-b0e1-11ea-839c-1e315a24e04b.png)
If I change this value again to 1, the problem is solved
![imagen](https://user-images.githubusercontent.com/13910563/84941630-f1dacd00-b0e1-11ea-86ab-8261a0ca8c29.png)

Thanks for your work.

**Comment by kurigohan0** [comment]
bump, same problem. Darkmet98, please, give me your tmx. Changing from 0 to 1 does not help me

**Comment by tge-was-taken** [comment]
I'm addressing this in an upcoming update.

**Comment by tge-was-taken** [comment]
Fixed by v1.9.1, set UserId to 1 in the UI
