### ISSUE TITLE
Model importing broken on 1.7.1

### ISSUE THREAD

**Issue by ShrineFox** [tge-was-taken/Amicitia#3]
The same fbx that would previously import with no issues on 1.6 results in major skinning errors when imported on 1.7.1:
![Before](https://cdn.discordapp.com/attachments/316239186736971776/417982182431129600/unknown.png)
Before
![After](https://cdn.discordapp.com/attachments/316239186736971776/417982352703356928/unknown.png)
After

**Comment by tge-was-taken** [comment]
Fixed in 1.8
